Fixes#6
brightlynxteam/bazaFront pull request #26
Opened 2019-08-08 18:50 UTC by aaivanov23

2019-08-08 20:34 UTC, otetcyablok requested changes

2019-08-08 20:34 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +        <div class="row items-center absolute-center">
`absolute-center` тут не нужен, чтобы не происходило такого:

![Screenshot 2019-08-08 at 23 08 36](https://user-images.githubusercontent.com/17749457/62734350-8213a480-ba31-11e9-944d-e7831a48b2e1.png)


Здесь лучше использовать `justify-center` и `text-center`.

2019-08-08 20:34 UTC, otetcyablok commented on src/pages/Info.vue
> +  <q-page class="q-px-md q-pb-md">
У `q-page` есть свойство `padding`. Давай использовать его. Надо заменить на `<q-page padding>` на всех страницах.

2019-08-08 20:34 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +            class="standard-link text-white q-mr-md"
`q-mr-md` на элементах стоит убрать, заменив использованием `q-gutter-md` на элементе выше.

2019-08-08 20:34 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +      <q-footer elevated class="bg-primary text-left q-py-lg q-px-md shadow-6">
Потому что нам не нужен прилипший намертво ко дну страницы `q-footer` (возможность отвязать его, по-моему, не предусмотрели), вместо него давай юзать обычный `footer`. Поэтому его и из компонентов в `quasar.conf.js` можно удалить.

2019-08-09 08:28 UTC, Xubunter commented on src/layouts/MainLayout.vue
> +      <q-footer elevated class="bg-primary text-left q-py-lg q-px-md shadow-6">
> Потому что нам не нужен прилипший намертво ко дну страницы `q-footer` (возможность отвязать его, по-моему, не предусмотрели), вместо него давай юзать обычный `footer`. Поэтому его и из компонентов в `quasar.conf.js` можно удалить.

А если изменить `<q-layout view="lHh Lpr lFf">` на `"lHh Lpr lff"`? Тогда ведь `q-footer` не будет прилипать

2019-08-09 09:02 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +      <q-footer elevated class="bg-primary text-left q-py-lg q-px-md shadow-6">
О, если это решает проблему, то пусть так, конечно

2019-08-10 22:12 UTC, otetcyablok approved these changes

2019-08-10 22:13 UTC, merged