Fixes#8
brightlynxteam/bazaFront pull request #27
Opened 2019-08-10 02:13 UTC by MaxEfimoff

2019-08-10 10:33 UTC, otetcyablok requested changes

2019-08-10 10:33 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +<template>
Вряд ли мы будем переиспользовать форму регистрации. Ей отдельный компонент не нужен

2019-08-10 10:33 UTC, otetcyablok commented on .eslintignore
> +/src/components/Auth/Registration.vue
Так делать не надо. `eslint` тут специально, чтобы за этими файлами следить, а ты их игнорировать собрался.

2019-08-10 10:33 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +        <div class="registrationHeader">Регистрация</div>
Давай сразу использовать переводы — `$t('registration')`. То же самое относительно всех текстов. Переводы находятся в `i18n/ru/index.js` и `i18n/en-us/index.js`.

2019-08-10 10:33 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +        <q-btn flat dense round @click="leftDrawerOpen = !leftDrawerOpen" aria-label="Menu">
Похоже, в этом файле никаких существенных изменений. Тогда не стоит его трогать — тем более что перенос делается, чтобы избежать километровых строк и увеличить читаемость.

2019-08-10 10:33 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +          val => isValidTelNumber(val) || 'Пожалуйста введите корректный номер телефона',
Маска тебе обеспечивает валидность ввода — это правило излишне

2019-08-10 10:33 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +    showPassword() {
Это стрём, скажу честно. Плюс, у тебя сейчас иконка не меняется при переключении режима. Посмотри код как сделан `Password with toggle` под разделом `Input types` здесь: https://quasar.dev/vue-components/input .

2019-08-10 10:33 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +    isPasswordsMatch(password2) {
Это может быть вычисляемым свойством — ему место в `computed`.

2019-08-10 10:33 UTC, otetcyablok commented on src/store/store-auth.js
> +const state = {
Объект юзера — это одни из основных данных, я не стал бы делать для них отдельный модуль. Нам нужно такое в основном стэйте:
```
state: {
  user: {},
},
getters: {
  loggedIn(state) {
    return Boolean(state.user.id);
  },
},
```

2019-08-10 10:33 UTC, otetcyablok commented on src/pages/Login.vue
> +    <h1 class="text-h2" v-text="$t('auth')" />
Пусть этот файл останется нетронутым

2019-08-10 10:33 UTC, otetcyablok commented on src/store/store-auth.js
> +      this.$router.push('/booking');
Перенаправление нужно сделать в routes.js, а эта функция не нужна.

2019-08-10 10:33 UTC, otetcyablok commented on src/store/store-auth.js
> +  async registerUser({ commit }, payload) {
Эта функция должна заниматься только отправлением данных и выплёвыванием ошибки, если всё плохо. Перенаправления здесь быть не должно. Оставь лучше её совсем пустой пока у нас нет бэка. Уведомление о произошедшем пиздеце тоже сделаем чуть иначе попозже (я про функцию `showErrorMessage`).

2019-08-10 10:33 UTC, otetcyablok commented on src/pages/Registration.vue
> +        <q-tabs
Табы? Зачем?

2019-08-10 10:33 UTC, otetcyablok commented on src/pages/Registration.vue
> -  name: 'Registration',
Верните

2019-08-10 10:38 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +        subscribed: 'false',
`'false'` -> `false`

2019-08-10 10:46 UTC, MaxEfimoff commented on src/layouts/MainLayout.vue
> +        <q-btn flat dense round @click="leftDrawerOpen = !leftDrawerOpen" aria-label="Menu">
Visual code переводит в одну строку при сохранении.

2019-08-10 10:47 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +          val => isValidTelNumber(val) || 'Пожалуйста введите корректный номер телефона',
Это условие было в тз, уберу.

2019-08-10 11:07 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +    showPassword() {
Ок, переделаю

2019-08-10 11:13 UTC, MaxEfimoff commented on src/pages/Login.vue
> +    <h1 class="text-h2" v-text="$t('auth')" />
Visual studio форматирует таким образом...

2019-08-10 11:19 UTC, MaxEfimoff commented on src/pages/Registration.vue
> +        <q-tabs
Ок, уберу.

2019-08-10 11:21 UTC, MaxEfimoff commented on src/pages/Registration.vue
> -  name: 'Registration',
Ок

2019-08-10 11:26 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +        subscribed: 'false',
По тз по умолчанию галочка не должна стоять, поэтому я поставил значение поля 'false'. Не понял, что не так.

2019-08-10 11:41 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +<template>
ок

2019-08-10 11:43 UTC, otetcyablok commented on src/components/Auth/Registration.vue
> +        subscribed: 'false',
У тебя строка, а не булево значение

2019-08-10 12:07 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +        subscribed: 'false',
понял)

2019-08-10 12:16 UTC, MaxEfimoff commented on src/store/store-auth.js
> +  async registerUser({ commit }, payload) {
Ок

2019-08-10 12:17 UTC, MaxEfimoff commented on src/store/store-auth.js
> +      this.$router.push('/booking');
Уберу

2019-08-10 12:37 UTC, MaxEfimoff commented on .eslintignore
> +/src/components/Auth/Registration.vue
ок

2019-08-10 15:56 UTC, MaxEfimoff commented on src/components/Auth/Registration.vue
> +    isPasswordsMatch(password2) {
ok

2019-08-11 12:54 UTC, otetcyablok approved these changes

2019-08-11 12:54 UTC, merged