update header (fixes #2)
brightlynxteam/bazaFront pull request #31
Opened 2019-08-12 09:58 UTC by KamaMakh

2019-08-13 09:30 UTC, otetcyablok requested changes

2019-08-13 09:30 UTC, otetcyablok commented on .eslintignore
> +/src/layouts/MainLayout.vue
Так делать не надо. Этот файл `должен` быть под ведомством `eslint`'а

2019-08-13 09:30 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +    next(vm => vm.isAuth = true);
Это мы будем делать иначе, в `router/index.js` через `Router.beforeEach`. Логике определения авторизации здесь не место.

В мастере уже начат модуль стора `user` — воспользуйся его геттером `loggedIn`.

2019-08-14 18:03 UTC, otetcyablok requested changes

2019-08-14 18:03 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +      return this.$store.getters['user/loggedIn'];
Используй `mapGetters`

2019-08-14 18:03 UTC, otetcyablok commented on src/router/routes.js
> +        path: 'auth',
Путь по заданию таким должен быть?

2019-08-14 18:07 UTC, otetcyablok commented on src/layouts/MainLayout.vue
> +              <router-link
Здесь тоже прошу соблюсти два пробела отступов

2019-08-14 18:08 UTC, otetcyablok commented on quasar.conf.js
> +      'Dialog',
Ты же его в этом бранче уже не используешь?

2019-08-14 18:23 UTC, KamaMakh commented on src/router/routes.js
> +        path: 'auth',
Тут https://github.com/brightlynxteam/bazaFront/issues/2, описано так:

1. Вход (path: /auth)
2. Регистрация (path: /registration)

2019-08-14 18:31 UTC, KamaMakh commented on src/router/routes.js
> +        path: 'auth',
Тут https://github.com/brightlynxteam/bazaFront/issues/2, описано так:

1. Вход (path: /auth)
2. Регистрация (path: /registration)

2019-08-15 12:03 UTC, otetcyablok approved these changes

2019-08-15 12:07 UTC, merged