Info block about Hutorok Fix( issue 4)
brightlynxteam/bazaFront pull request #36
Opened 2019-08-15 15:28 UTC by AllenWolker

2019-08-15 17:31 UTC, otetcyablok requested changes

2019-08-15 17:31 UTC, otetcyablok commented on src/pages/Index.vue
> -    <booking-card />
Это тут неспроста. Карточка брони тоже должна быть на главной

2019-08-15 17:31 UTC, otetcyablok commented on src/router/routes.js
> +        component: () => import('pages/Thermal.vue'),
Ведь нет у тебя в бранче этих файлов. Тебе разве ошибку квазар не кидает? Нужно сделать пустые файлы (подобные в проекте уже есть)

2019-08-15 17:31 UTC, otetcyablok commented on src/pages/Index.vue
> +  import InfoHutorok from '../components/InfoAboutHutorok.vue';
Компонент нужен либо чтобы инкапсулировать логику, либо упростить переиспользование. Похоже ни то, ни другое не является твоим кейсом

2019-08-15 17:31 UTC, otetcyablok commented on src/components/InfoAboutHutorok.vue
> +      <label for="virtualBase">Виртуальная прогулка по базе</label>
Ты же используешь уже один перевод, почему здесь без них?

2019-08-15 17:31 UTC, otetcyablok commented on src/components/InfoAboutHutorok.vue
> +    <router-link to="/thermal">
Может тут стоит использовать элемент `QCard`?

https://quasar.dev/vue-components/card

2019-08-15 17:31 UTC, otetcyablok commented on src/pages/InfoAboutHutorok.vue
> +<template>
Вроде, не должно быть такой страницы

2019-08-15 17:31 UTC, otetcyablok commented on src/pages/Index.vue
>    <q-page class="flex flex-center">
Тут надо будет исправить на `<q-page padding>`

2019-08-15 21:30 UTC, AllenWolker commented on src/router/routes.js
> +        component: () => import('pages/Thermal.vue'),
Делал, локально, просто не добавлял их сюда. Они ведь будут конфликтовать с тем что у же есть, если они уже есть.

2019-08-15 21:31 UTC, AllenWolker commented on src/pages/Index.vue
> -    <booking-card />
У меня была более старая версия  главной ветки, в ней еще не было  этой части..

2019-08-15 21:33 UTC, AllenWolker commented on src/pages/InfoAboutHutorok.vue
> +<template>
В Fix, перенес ее в компоненты.

2019-08-15 21:39 UTC, AllenWolker commented on src/pages/Index.vue
> +  import InfoHutorok from '../components/InfoAboutHutorok.vue';
Ну, в этом модуле может что-нибудь измениться, вот я его и вынес в компоненты, перенесу на главную.

2019-08-15 21:40 UTC, AllenWolker commented on src/pages/Index.vue
> +  import InfoHutorok from '../components/InfoAboutHutorok.vue';
> Компонент нужен либо чтобы инкапсулировать логику, либо упростить переиспользование. Похоже ни то, ни другое не является твоим кейсом

В этом модуле может что-нибудь измениться, вот я его и вынес в компоненты, перенесу на главную.

2019-08-15 21:40 UTC, AllenWolker commented on src/router/routes.js
> +        component: () => import('pages/Thermal.vue'),
> Ведь нет у тебя в бранче этих файлов. Тебе разве ошибку квазар не кидает? Нужно сделать пустые файлы (подобные в проекте уже есть)

Делал, локально. Просто не добавлял их сюда. Они ведь будут конфликтовать с тем что у же есть, если они уже есть.

2019-08-15 21:41 UTC, AllenWolker commented on src/pages/Index.vue
> -    <booking-card />
> Это тут неспроста. Карточка брони тоже должна быть на главной

У меня была более старая версия главной ветки, в ней еще не было этой части..

2019-08-15 21:41 UTC, AllenWolker commented on src/pages/InfoAboutHutorok.vue
> +<template>
> Вроде, не должно быть такой страницы

В Fix, перенес ее в компоненты.

2019-08-15 21:51 UTC, AllenWolker commented on src/components/InfoAboutHutorok.vue
> +      <label for="virtualBase">Виртуальная прогулка по базе</label>
> Ты же используешь уже один перевод, почему здесь без них?

Эм, непонял..

2019-08-25 17:07 UTC, otetcyablok commented on src/router/routes.js
> +        component: () => import('pages/Thermal.vue'),
Конфликтов бояться — в разработку не ходить

2019-08-25 17:13 UTC, closed without merging