Block pages Support center (fixes#23)
brightlynxteam/bazaFront pull request #37
Opened 2019-08-16 17:17 UTC by sergeykorolov

2019-08-16 20:21 UTC, otetcyablok requested changes

2019-08-16 20:21 UTC, otetcyablok commented on src/router/routes.js
> +        path: 'info/booking',
не та страница. Здесь будет страница бронирования. Сделай новую `BookingInfo.vue`. Давай соберём их в папке `pages/info`.

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +              val => isValidPhoneNumber || $t('enter_correct_tel_number'),
Ненужная проверка. Маска уже обеспечивает ввод только чисел. Используй ещё свойство `unmask-value`

2019-08-16 20:21 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  send_message: 'Отправить',
Ключ `send` подходит лучше

2019-08-16 20:21 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  number_characters_question: 'Скорректируйте, пожалуйста, вопрос',
Ключ не соответствует переводу. Пусть лучше это будет `correct_question_message` или что-то в этом духе

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +        this.$store.dispatch('/sendMessage', this.formData)
Здесь должно быть название экшна, а не путь. То есть в сторе должен быть сделан экшн, относимый к твоим нуждам. К сожалению, пока на бэке соответствующий рут не создан. Постараюсь пнуть по этому поводу.

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +            <p class="requestSent text-green"
Вместо этого лучше использовать
```
this.$q.notify({
  icon: 'done',
  color: 'positive',
  message: this.$t('request_sent'),
});
```
после вызова экшна стора, где у тебя сейчас вызывается функция `showMessage`

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +              val => isValidEmailAddress || $t('enter_correct_email'),
Пожалуй, хватит дублировать код. Нужно сделать примесь `emailValidationMixin`, положить её в папку `components/helpers` и заиспользовать везде, где проверяется почта.

Как делать примеси во `Vue` знаешь?

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +  .submitWrapper{
Вместо него можно использовать класс `relative-position`

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +  .requestSent{
Класс будет не нужен после того, как заменишь на `this.$q.notify`, но на будущее:

1) давай использовать написание классов через дефис, а не `camelCase`;
2) его можно было бы заменить уже имеющимся в коробке классом `absolute-right`.

Список классов, относимых к позиционированию:

https://quasar.dev/style/positioning

В разделе `Style & Identity` остальные имеющиеся классы.

2019-08-16 20:21 UTC, otetcyablok commented on src/pages/Faq.vue
> +      showMessage: false,
Надобность этого отпадёт после замены на `this.$q.notify`

2019-08-19 10:02 UTC, sergeykorolov commented on src/i18n/ru/index.js
> +  number_characters_question: 'Скорректируйте, пожалуйста, вопрос',
Мне кажется сообщение не понятно для юзера. Там ограничения по количеству символов. Может лучше будет выводить сообщение про недобор или перебор символов?

2019-08-19 12:19 UTC, sergeykorolov commented on src/pages/Faq.vue
> +              val => isValidEmailAddress || $t('enter_correct_email'),
с примесями разобрался вроде)

2019-08-23 13:48 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  number_characters_question: 'Скорректируйте, пожалуйста, вопрос',
Согласен с тем, что не понятно. Поправим потом, если надо будет

2019-09-01 18:59 UTC, otetcyablok approved these changes

2019-09-01 18:59 UTC, merged