Fixes#5
brightlynxteam/bazaFront pull request #38
Opened 2019-08-17 16:07 UTC by ArthurAbd

2019-08-18 10:05 UTC, otetcyablok requested changes

2019-08-18 10:05 UTC, otetcyablok commented on src/store/urls.js
> +const servicesUrl = 'https://jsonplaceholder.typicode.com/photos?_limit=10';
На бэке уже есть рут `${serverUrl}/services/getAllServices`

2019-08-18 10:05 UTC, otetcyablok commented on src/store/service/getters.js
> +  return state.services;
Этот геттер бесполезен. Ничем не лучше прямого обращения к свойству стора

2019-08-18 10:05 UTC, otetcyablok commented on src/store/index.js
> +import service from './service';
Слишком специфичный модуль получится. Давай сделаем модуль `content`, который к контенту сайта относится будет.

2019-08-18 10:05 UTC, otetcyablok commented on src/components/Recommend.vue
> +    if (isNaN(this.slide)) this.slide = this.allServices[0].id;
Чтобы не подчёркивало: `Number.isNaN(Number(this.slide))`. Но: почему бы сразу не начать с первого `id` в `data`?

2019-08-18 10:05 UTC, otetcyablok commented on src/store/service/actions.js
> +function register({ commit }, data) {
Зачем это здесь?

2019-08-18 10:05 UTC, otetcyablok commented on src/store/service/mutations.js
> +function setUser(state, user) {
тоже не нужно здесь

2019-08-18 10:05 UTC, otetcyablok commented on src/store/service/mutations.js
> +function resetUser(state) {
и снова не нужно здесь

2019-08-18 10:05 UTC, otetcyablok commented on src/store/service/mutations.js
> +function updateServices(state, services) {
`setServices`, давай пойдём по этой дорожке в наименованиях

2019-08-18 10:05 UTC, otetcyablok commented on src/components/Recommend.vue
> +a {
Используй класс для этого лучше

2019-08-18 12:54 UTC, ArthurAbd commented on src/components/Recommend.vue
> +    if (isNaN(this.slide)) this.slide = this.allServices[0].id;
Я подумал, вдруг будет удаление услуги, и id: 1 останется не используемый?

2019-08-18 13:00 UTC, ArthurAbd commented on src/store/service/getters.js
> +  return state.services;
Сделать прямое обращение?

2019-08-19 16:30 UTC, otetcyablok requested changes

2019-08-19 16:30 UTC, otetcyablok commented on src/store/content/actions.js
> +    axios.get(servicesUrl)
Создаётся впечатление, что ты не смотрел свой код после изменений. `axios.get` работать не будет, `axios.post` — будет.

2019-08-19 16:30 UTC, otetcyablok commented on src/store/content/actions.js
> +        commit('setServices', response.data);
Здесь потребуется изменение. `axios` да, отдаёт запрос в свойстве `data`, но далее ещё будет вложенность

2019-08-19 16:30 UTC, otetcyablok commented on src/components/Recommend.vue
> +    if (Number.isNaN(Number(this.slide))) this.slide = this.allServices[0].id;
Ты получишь массив услуг от бэкенда — и по нему будешь проходиться, показывая каждый элемент. Не будет такой ситуации, что элемент вдруг самоудалится.

Предполагаю, что начальной ситуацией у тебя будет `slideId: 0`.

2019-08-19 16:30 UTC, otetcyablok commented on src/components/Recommend.vue
> +          <router-link class="none-decor" :to="'/services/' + service.id">
В перенаправлениях давай сразу использовать имена рутов. Значит, нужно создать пустую (если это не в рамках твоего таска) страницу услуги, описать её в `routes.js` и заиспользовать здесь имя нового рута.

2019-08-19 16:30 UTC, otetcyablok commented on src/components/Recommend.vue
> +              <div><img :src="service.url"></div>
На бэке в ответе не сделали ещё картинки, к сожалению. Добавь, пожалуйста, любую картинку в `src/statics/...` и заиспользуй здесь, чтобы сразу было понятно, как это будет выглядеть (а к тому моменту, может, и бэк подоспеет). Потом просто заменим на полученный от бэка путь.

2019-08-19 16:32 UTC, otetcyablok commented on src/store/service/getters.js
> +  return state.services;
А в этом лучше сразу разобраться.

Не сразу подгружается потому, что отрисовка не ждёт `mounted`, пока тот получит данные.

2019-08-19 16:35 UTC, otetcyablok commented on src/components/Recommend.vue
> +  methods: mapActions('content', ['getServices']),
Топлю за то, чтобы не мапать экшны, а вместо этого писать эксплицитно `this.$store.state.dispatch('content/getServices')`, потому что все использования экшнов будет легче найти и они не будут теряться в массиве методов компонентов.

2019-08-25 17:00 UTC, otetcyablok approved these changes

2019-08-25 17:00 UTC, merged