Fixes #19
brightlynxteam/bazaFront pull request #40
Opened 2019-08-22 20:07 UTC by alexandra231

2019-08-23 14:43 UTC, otetcyablok requested changes

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      rooms: [
`rooms` нужно забрать с бэка — путь `/rooms/getAllRooms`.

Для всех подобных дел, думаю, стоит сделать отдельный модуль стора `houses`, к примеру.

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      housing: [
Тоже нужно забрать с бэка, сохранив при этом возможность выбрать все — путь `/housings/getAllHousings`.

2019-08-23 14:43 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  roomsAndHouses: 'Номера и домики',
Я тоже за `camelCase` вообще, но мы уже начали писать по-змеиному здесь. Продолжим традицию

2019-08-23 14:43 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  roomNumber: 'Номер ',
С пробелами не лучшее решение. Тут либо пробел переносить в место использования перевода, либо использовать плэйсхолдер `{0}` в переводе, передавая его значение вторым элементом `$t('room_number', [11])`

2019-08-23 14:43 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  pricePerDay: 'Цена за ночь ',
Так за день или за ночь?

2019-08-23 14:43 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  person: 'Кол-во человек ',
По ключу `person` я бы ожидал перевода `человек`

2019-08-23 14:43 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  sortByPricePerDay: 'Сортировка по цене за ночь',
Та же дилемма: день или ночь?

2019-08-23 14:43 UTC, otetcyablok commented on src/router/routes.js
> +        name: 'roomItem',
Имена рутов называем через дефис. Но пусть этот рут будет назван `room`.

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      if (this.isSort) {
Строго говоря, это не `isSort`, а `isDesc` или `isAsc` — как оно там.

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +          {label: $t('list'), value: true},
Может, заиспользовать здесь иконки `view_headline` и `view_module`?

https://material.io/resources/icons/ — здесь можно увидеть, как оно выглядит

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      <div class="q-pa-md col-xs-12 col-sm-4 col-md-2">
Вот эту штуку надо предусмотреть:

![Screenshot 2019-08-23 at 17 33 33](https://user-images.githubusercontent.com/17749457/63600408-2e29c380-c5cc-11e9-9011-ebadf12f1fd1.png)

Она возникает, если на широком (но недостаточно широком) экране открыть меню.

2019-08-23 14:43 UTC, otetcyablok commented on src/pages/Rooms.vue
> +          :label="$t('sortByPricePerDay')">
Как-то надо показать направление сортировки. Да и кнопка выглядит громоздко, но это надо придумать сначала, как она должна выглядеть.

2019-08-23 20:24 UTC, alexandra231 commented on src/pages/Rooms.vue
> +      rooms: [
по информации от Димы, бэка не было, поэтому и стоят заглушки. если бэк готов, то могу вынести во vuex

2019-08-23 20:27 UTC, alexandra231 commented on src/i18n/ru/index.js
> +  pricePerDay: 'Цена за ночь ',
тогда уж и не день и не ночь)правильнее наверное будет цена за сутки

2019-08-23 23:35 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      rooms: [
Понимаю. Написал рабочие руты

2019-08-23 23:38 UTC, otetcyablok commented on src/i18n/ru/index.js
> +  pricePerDay: 'Цена за ночь ',
Давай сутки тогда.

https://github.com/brightlynxteam/bazaFront/issues/19 — в задании тоже сутки тем более.

2019-08-24 15:55 UTC, alexandra231 commented on src/pages/Rooms.vue
> +      if (this.isSort) {
мне просто поменять название переменной?

2019-08-28 09:19 UTC, otetcyablok commented on src/pages/Rooms.vue
> +      if (this.isSort) {
Да

2019-09-01 13:22 UTC, otetcyablok approved these changes

2019-09-01 13:22 UTC, merged